theme = "catppuccin_frappe"

[editor]
line-number = "relative"
mouse = false
color-modes = true
cursorline = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "😅"
mode.insert = "😤"
mode.select = "😭"
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
