# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/chun/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Plugins

source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Customize part

# bob
export PATH=${PATH}:~/.local/share/bob/nvim-bin

# neofetch
# neofetch
alias n="neofetch"

# proxy
function proxy_on() {
	export https_proxy=http://127.0.0.1:7890
	export http_proxy=http://127.0.0.1:7890
	export all_proxy=socks5://127.0.0.1:7890
	export ftp_proxy=$http_proxy
	export rsync_proxy=$http_proxy
	export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
	echo "Proxy environment variable set."
}

function WSL_proxy_on() {
	host_ip=$(cat /etc/resolv.conf |grep "nameserver" |cut -f 2 -d " ")
	export all_proxy="socks5://$host_ip:7890"
}

function proxy_off(){
	unset http_proxy https_proxy ftp_proxy rsync_proxy all_proxy no_proxy \
		HTTP_PROXY HTTPS_PROXY FTP_PROXY RSYNC_PROXY
			echo -e "Proxy environment variable removed."
		}

# Toggle Proxy
# function proxy_on() {
#     export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
#
#     if (( $# > 0 )); then
#         valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}.\?\)\{4\}:\([0-9]\+\)/&/p')
#         if [[ $valid != $@ ]]; then
#             >&2 echo "Invalid address"
#             return 1
#         fi
#         local proxy=$1
#         export http_proxy="$proxy" \
#                https_proxy=$proxy \
#                ftp_proxy=$proxy \
#                rsync_proxy=$proxy
#         echo "Proxy environment variable set."
#         return 0
#     fi
#
#     echo -n "username: "; read username
#     if [[ $username != "" ]]; then
#         echo -n "password: "
#         read -es password
#         local pre="$username:$password@"
#     fi
#
#     echo -n "server: "; read server
#     echo -n "port: "; read port
#     local proxy=$pre$server:$port
#     export http_proxy="$proxy" \
#            https_proxy=$proxy \
#            ftp_proxy=$proxy \
#            rsync_proxy=$proxy \
#            HTTP_PROXY=$proxy \
#            HTTPS_PROXY=$proxy \
#            FTP_PROXY=$proxy \
#            RSYNC_PROXY=$proxy
# }
